### ISSUE TITLE
Does this pull in nested dependencies?

### ISSUE THREAD

**Issue by kevana** [DGolubets/js-module-loader#1]
I didn't see any test cases that show an A depends on B depends on C situation like:

```
define('A', ['B'], function(B){
    return {
       text: 'Module A'
    };
});
. . .
define('B', ['C'], function(C){
    return {
       text: 'Module B'
    };
});
```

**Comment by DGolubets** [comment]
Yes it does.

[Here is the test for common dependency](https://github.com/DGolubets/js-module-loader/blob/master/src/test/scala/ru/dgolubets/jsmoduleloader/api/amd/AmdLoaderSpec.scala#L108), which is even a bit more complex scenario: A depends on B and C, B and C both depend on D.

**Comment by kevana** [comment]
Great, missed that when I was skimming the code, thanks.
